#cloud-config
coreos:
  units:
    - name: docker.service
      command: start
    - name: backend.service
      command: start
      content: |
        [Unit]
        Description=Backend Service
        After=docker.service
        Requires=docker.service

        [Service]
        TimeoutStartSec=0
        ExecStartPre=-/usr/bin/docker kill backend
        ExecStartPre=-/usr/bin/docker rm backend
        ExecStartPre=/usr/bin/docker pull whalesalad/docker-django-poc
        ExecStart=/usr/bin/docker run --name backend -p 80:8080 whalesalad/docker-django-poc
        ExecStop=/usr/bin/docker stop backend
  update:
    group: alpha
    reboot-strategy: off
